language: python
python:
    - "3.6"

install:
    - bash install.sh
    - . $HOME/miniconda/etc/profile.d/conda.sh
    - conda activate comcat
services:
    - xvfb
before_script:
    # This is to take care of Invalid DISPLAY variable
    - "export DISPLAY=:99.0"
    - sleep 3 # give xvfb some time to start
script:
    - export PYTHONPATH="."
    - echo `which py.test`
    - py.test --ignore=tests/bin/ --cov=libcomcat
after_success:
    - pip install codecov codacy-coverage
    - codecov
    - coverage xml
    - python-codacy-coverage -r coverage.xml
    - bash <(curl -s https://codecov.io/bash)
